---
title: "Ryan's Base_R approach"
output: html_notebook
---


```{r}
# Read in data and split into two frames
# data <- read.csv("C:/Users/rcd2/Desktop/data.csv")

## Example Data

country <- c("A","B","C","D","A","E","F","X","Y","Z","Q","R")
dispute <- c(1,1,1,1,2,2,2,3,3,3,3,3)
side_a <- c(0,0,1,1,0,1,1,0,0,0,1,1)
side_b <- c(1,1,0,0,1,0,0,1,1,1,0,0)

country_df <- data_frame(country, dispute, side_a, side_b)

country_df

data <- country_df

data
```


```{r}
country_a <- subset(data,side_a == 1)
country_b <- subset(data,side_b == 1)

country_a
country_b
```


```{r}
# Rename country field so they don’t conflict when we merge
names(country_a)[names(country_a) == 'country'] <- 'country_a'
names(country_b)[names(country_b) == 'country'] <- 'country_b'

country_a
country_b
```


```{r}
# Drop side_a and side_b
drop <- c("side_a", "side_b")
country_a = country_a[,!names(country_a) %in% drop]
country_b = country_b[,!names(country_b) %in% drop]

country_a
country_b
```


```{r}
# Merge (SQL outer join)
output <- merge(x=country_a, y=country_b, by = "dispute", all=TRUE)

output
```



